### ISSUE TITLE
It doesn't work with Google Cloud Storage Provider

### ISSUE THREAD

**Issue by kevinblanco** [strapi-community/strapi-plugin-local-image-sharp#11]
Hello, 

My Strapi instance runs on google cloud and stores the files in GCP, the parameters doesn't seem to work. Any ideas?

THanks in advance

**Comment by stafyniaksacha** [comment]
Hello, same answer as #9 :

This cannot be done since when you're accessing images through 3rd party services: their servers will handle the requests. To be able to perform such transformation, you will need to proxy them, but you will lose their benefits (edge, cdn, etc..)

Instead, you can use this plugin and use 3rd party caching service (cloudflare, varnish, ...).

I'm closing this issue since we cannot do anything. You still can reopen a [discussions](https://github.com/strapi-community/strapi-plugin-local-image-sharp/discussions)
