### ISSUE TITLE
Question: how would this work if I use AWS S3 provider?

### ISSUE THREAD

**Issue by Antoine-lb** [strapi-community/strapi-plugin-local-image-sharp#9]
Hello 👋

Is this plugin still useful if I use a provider?

Thanks!

**Comment by KeystoneScience** [comment]
+1

**Comment by davidwindell** [comment]
Yeah we'd love this too

**Comment by BorisKamp** [comment]
Yeah guys! I need this as well. Got a feeling everybody's working with a 3rd party upload provider at this moment...

**Comment by stafyniaksacha** [comment]
Hello everyone, 

This cannot be done since when you're accessing images through 3rd party services: their servers will handle the requests. To be able to perform such transformation, you will need to proxy them, but you will lose their benefits (edge, cdn, etc..)

Instead, you can use this plugin and use 3rd party caching service (cloudflare, varnish, ...).

I'm closing this issue since we cannot do anything. You still can reopen a [discussions](https://github.com/strapi-community/strapi-plugin-local-image-sharp/discussions)
